title: Muhammad Ishaque
logo: <div style="width: 150px; height: 150px; border-radius: 50%; overflow: hidden;"><img src="/assets/img/pic.jpg" alt="Logo" style="width: 100%; height: auto;"></div>
description: Data Scientist
show_downloads: true
theme: jekyll-theme-minimal
